### ISSUE TITLE
Some questions about the code and paper

### ISSUE THREAD

**Issue by LqNoob** [li1jkdaw/gaussian_lpcnet#1]
Hi, thanks for your great project.

But I have some questions for your code and paper -- <Fast and lightweight on-device TTS with Tacotron2 and LPCNet>.

> Please note that it is not a real multhithread implementation of parallel LPCNet. It is just the simulation of it in order to get audio records which sound as if they were synthesized in a parallel manner.

What does this passage mean? Because after reading your code, no relevant parallel implementation was found. But in your paper, there are related multi-thread statistics. How did you implement parallel lpcnet?

> The whole TTS application requires only 12.5Mb of storage (11.4Mb for Tacotron2 and 1.1Mb for LPCNet).

How do you keep lpcnet with such a small storage, and is there any change between this implementation and [mozilla](https://github.com/mozilla/LPCNet)'s lpcnet?

**Comment by li1jkdaw** [comment]
Hi, @LqNoob !
1) Actual multi-thread LPCNet inference was implemented with optimizations for Huawei mobile phones with specific hardware. We report inference speed for these specific CPUs in Table 3 but unfortunately we can't share this code. 
So, what you see in this repository is not multi-thread code: inference is autoregressive but the frames which are meant to be processed in different threads are synthesized independently (e.g. we don't use RNN state from frame t-1 while processing frame t if a "splitting" algorithm tells us that frames t-1 and t can be processed in different threads). That's what the passage you mentioned means.
2) The model itself is absolutely the same as in mozilla repository. We use quantization to store all weights of LPCNet as 8-bit numbers. Also, we apply compression algorithm (check https://github.com/facebook/zstd).

**Comment by LqNoob** [comment]
Hi, @li1jkdaw! 

Thank you for your kindly reply, this is very helpful for me.
